name: "Comprueba hitos y milestones"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[1234567].md'
      - '!objetivos/*.(md|org)'

jobs:
  obtain-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v1
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Comprueba hitos e issues
        uses: JJ/repo-in-diff-gh-action@releases/v0
        with:
          github-token: ${{github.token}}
          minMilestones: 3
